import re
from typing import Dict, List, Tuple

from appify.common.doc_parser.doc_parser import DocParser
from appify.common.parameter_info import ParameterInfo, ParameterName


def count_leading_space(line) -> int:
    return len(line) - len(line.lstrip())


class RestructuredParser(DocParser):
    NAME: str = ...
    DESCRIPTION: str = ...
    TYPE_INFO: str = ...
    TYPE_INFO_DESCRIPTION: str = ...
    TYPE_INFO_TYPE: str = ...
    REGEX: str = ...

    def __init__(self):
        self._regex: re.Pattern = ...

    def parse(self, docstring: str) -> Dict[ParameterName, ParameterInfo]:
        ...

    @staticmethod
    def _get_info_text(lines: List[str], index: int, length: int) -> Tuple[int, str]:
        ...
